import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  title: {
    fontSize: 38,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 56,
    letterSpacing: 0.6,
    textShadowColor: 'rgba(8, 145, 178, 0.15)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
    lineHeight: 48,
  },
  input: {
    width: '100%',
    height: 62,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingHorizontal: 24,
    marginBottom: 20,
    fontSize: 16.5,
    color: '#0F172A',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
    lineHeight: 24,
  },
  buttonRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginTop: 20,
    gap: 16,
  },
  loginButton: {
    backgroundColor: '#0891B2',
    paddingVertical: 22,
    paddingHorizontal: 56,
    borderRadius: 22,
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
    overflow: 'hidden',
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: 18.5,
    fontWeight: '800',
    letterSpacing: 0.5,
    lineHeight: 26,
  },
  forgotPassword: {
    color: '#64748B',
    fontSize: 15.5,
    fontWeight: '600',
    textDecorationLine: 'underline',
    lineHeight: 24,
    opacity: 0.9,
  },
  signupContainer: {
    marginTop: 40,
  },
  signupText: {
    color: '#64748B',
    fontSize: 15.5,
    fontWeight: '600',
    lineHeight: 24,
  },
  welcomeContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'space-around',
    padding: 36,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 56,
  },
  logo: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#0891B2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.45,
    shadowRadius: 28,
    elevation: 14,
    borderWidth: 5,
    borderColor: '#FFFFFF',
  },
  logoText: {
    fontSize: 68,
    lineHeight: 68,
  },
  logoName: {
    fontSize: 32,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: 1.6,
    lineHeight: 38,
  },
  welcomeTitle: {
    fontSize: 34,
    color: '#0F172A',
    textAlign: 'center',
    fontWeight: '700',
    marginBottom: 10,
    letterSpacing: 0.4,
    lineHeight: 42,
  },
  welcomeBrand: {
    fontSize: 46,
    fontWeight: '800',
    color: '#0891B2',
    textAlign: 'center',
    marginTop: -2,
    letterSpacing: 3,
    textShadowColor: 'rgba(8, 145, 178, 0.25)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 12,
    lineHeight: 54,
  },
  socialContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 32,
    marginVertical: 32,
  },
  socialButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#0891B2',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 12,
    borderWidth: 3.5,
    borderColor: '#FFFFFF',
  },
  socialIcon: {
    fontSize: 38,
    color: '#FFFFFF',
    lineHeight: 38,
  },
  actionButtons: {
    marginBottom: 48,
    gap: 16,
    width: '100%',
    alignItems: 'center',
  },
  loginLink: {
    color: '#0891B2',
    fontSize: 17.5,
    textAlign: 'center',
    fontWeight: '700',
    paddingVertical: 18,
    paddingHorizontal: 28,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginVertical: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 5,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    minWidth: '92%',
    lineHeight: 26,
  },
  personalInfoContainer: {
    flexGrow: 1,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    paddingTop: 68,
    paddingHorizontal: 36,
    paddingBottom: 60,
  },
  personalInfoTitle: {
    fontSize: 36,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 44,
    letterSpacing: 0.6,
    textShadowColor: 'rgba(8, 145, 178, 0.15)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
    lineHeight: 44,
  },
  row: {
    flexDirection: 'row-reverse',
    width: '100%',
    justifyContent: 'space-between',
    gap: 16,
  },
  halfInput: {
    width: '48%',
  },
  nextButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#0891B2',
    paddingVertical: 22,
    paddingHorizontal: 48,
    borderRadius: 22,
    marginTop: 36,
    gap: 18,
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
    overflow: 'hidden',
  },
  nextButtonText: {
    color: '#FFFFFF',
    fontSize: 18.5,
    fontWeight: '800',
    letterSpacing: 0.5,
    lineHeight: 26,
  },
  arrow: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 34,
  },
});