import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  title: {
    fontSize: 38,
    fontWeight: '800',
    color: '#0891B2',
    marginBottom: 52,
    letterSpacing: 0.8,
    textShadowColor: 'rgba(8, 145, 178, 0.1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  input: {
    width: '100%',
    height: 58,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 20,
    marginBottom: 18,
    fontSize: 16,
    color: '#1F2937',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  buttonRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginTop: 8,
  },
  loginButton: {
    backgroundColor: '#0891B2',
    paddingVertical: 18,
    paddingHorizontal: 52,
    borderRadius: 14,
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 0,
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  forgotPassword: {
    color: '#6B7280',
    fontSize: 15,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  signupContainer: {
    marginTop: 32,
  },
  signupText: {
    color: '#6B7280',
    fontSize: 15,
    fontWeight: '500',
  },
  welcomeContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'space-around',
    padding: 28,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 48,
  },
  logo: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#0891B2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 12,
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  logoText: {
    fontSize: 60,
  },
  logoName: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1F2937',
    letterSpacing: 1.2,
  },
  welcomeTitle: {
    fontSize: 32,
    color: '#0891B2',
    textAlign: 'center',
    fontWeight: '700',
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  welcomeBrand: {
    fontSize: 40,
    fontWeight: '800',
    color: '#0891B2',
    textAlign: 'center',
    marginTop: -6,
    letterSpacing: 2.5,
    textShadowColor: 'rgba(8, 145, 178, 0.15)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  socialContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 24,
    marginVertical: 24,
  },
  socialButton: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: '#0891B2',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  socialIcon: {
    fontSize: 34,
    color: '#FFFFFF',
  },
  actionButtons: {
    marginBottom: 40,
    gap: 12,
    width: '100%',
    alignItems: 'center',
  },
  loginLink: {
    color: '#0891B2',
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '600',
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginVertical: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    minWidth: '90%',
  },
  personalInfoContainer: {
    flexGrow: 1,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 28,
    paddingBottom: 50,
  },
  personalInfoTitle: {
    fontSize: 36,
    fontWeight: '800',
    color: '#0891B2',
    marginBottom: 40,
    letterSpacing: 0.8,
    textShadowColor: 'rgba(8, 145, 178, 0.1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  row: {
    flexDirection: 'row-reverse',
    width: '100%',
    justifyContent: 'space-between',
    gap: 12,
  },
  halfInput: {
    width: '48%',
  },
  nextButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#0891B2',
    paddingVertical: 18,
    paddingHorizontal: 40,
    borderRadius: 14,
    marginTop: 28,
    gap: 14,
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 0,
  },
  nextButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  arrow: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '800',
  },
});